# Generated by Django 5.2.18 on 2026-10-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField(default=list)),
                ('recipe', models.JSONField(default=dict)),
                ('cooking_instructions', models.JSONField(default=list)),
                ('social_media_post', models.JSONField(default=dict)),
                ('platform', models.CharField(default='Instagram', max_length=40)),
                ('prompt', models.TextField(blank=True)),
                ('prompt_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
