# Generated by Django 5.2.18 on 2026-10-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('ingredients', models.JSONField(default=list)),
                ('additional_ingredients', models.JSONField(default=list)),
                ('servings', models.PositiveIntegerField(default=4)),
                ('preparation_time', models.CharField(max_length=40)),
                ('cooking_time', models.CharField(max_length=40)),
                ('difficulty', models.CharField(max_length=40)),
                ('instructions', models.JSONField(default=list)),
                ('match_percentage', models.PositiveSmallIntegerField(default=0)),
                ('available_ingredients', models.JSONField(default=list)),
                ('missing_ingredients', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
